# 02 - Phase 1 Screening (4 models x 16 covariates x 2 windows x 2 horizons = 256 experiments)

Tujuan: screening single-covariate untuk mencari covariate mana yang memberi improvement signifikan terhadap baseline (target-only) di 4 model tree-based.

## Desain
- **Models (4):** RandomForest, ExtraTrees, XGBoost, LightGBM
- **Covariates (16):** None (baseline) + 15 single covariates
- **Windows (2):** 30, 120
- **Horizons (2):** 1 hari (next-day), 30 hari (one-month ahead)
- **CV:** 5-fold expanding window
- **Hyperparameters:** default konservatif dari spec (bukan arbitrary)
- **Metric utama:** MAPE di level harga IHSG (bukan log-diff)

## Output
- `phase1_screening_results.csv` - 256 rows, semua metrik per experiment
- `phase1_screening_analysis.csv` - pass/fail per covariate (threshold 0.3% improvement)

## 1. Imports & Load Data

In [ ]:
import pandas as pd
import numpy as np
import joblib
import gc
import glob
import traceback
from datetime import datetime
import warnings

from darts import TimeSeries
from darts.models import RandomForestModel, XGBModel, LightGBMModel
from darts.dataprocessing.transformers import Scaler, Diff
from darts.utils.missing_values import fill_missing_values
from sklearn.ensemble import ExtraTreesRegressor

try:
    from darts.models import SKLearnModel
except ImportError:
    from darts.models import RegressionModel as SKLearnModel

warnings.filterwarnings("ignore")

# Auto-load df_merged terbaru (tidak hardcode nama file)
joblib_files = sorted(glob.glob("saved_models/df_merged_*.joblib"), reverse=True)
if not joblib_files:
    raise FileNotFoundError("df_merged_*.joblib tidak ditemukan. Jalankan notebook 00 dulu.")
df_merged = joblib.load(joblib_files[0])
print(f"Loaded: {joblib_files[0]}")

LEVEL_VARS = ["M2", "USDIDR", "Coal", "Copper", "Nickel", "Silver", "Tin", "STI", "Gold", "WTI", "GDP"]
RATE_VARS  = ["BI_Rate", "CPI", "NPL_Ratio", "US_Treasury_10Y"]

print(f"Data: {df_merged.shape} | {df_merged['date'].min().date()} to {df_merged['date'].max().date()}")

## 2. Konfigurasi Eksperimen

In [ ]:
SINGLE_COVARIATES = {
    "None":            [],
    # Macro (7)
    "BI_Rate":         ["BI_Rate"],
    "CPI":             ["CPI"],
    "M2":              ["M2"],
    "NPL_Ratio":       ["NPL_Ratio"],
    "USDIDR":          ["USDIDR"],
    "GDP":             ["GDP"],
    "US_Treasury_10Y": ["US_Treasury_10Y"],
    # Commodity (7)
    "Coal":            ["Coal"],
    "Copper":          ["Copper"],
    "Nickel":          ["Nickel"],
    "Silver":          ["Silver"],
    "Tin":             ["Tin"],
    "Gold":            ["Gold"],
    "WTI":             ["WTI"],
    # Regional (1)
    "STI":             ["STI"],
}

WINDOWS  = [20, 120] # 1 bulan business day, 6 bulan business day
HORIZONS = [1, 20]     # 1 hari, 1 bulan business day
N_FOLDS  = 5

# Default hyperparameters (spec-based, bukan arbitrary)
MODEL_CONFIGS = {
    "RandomForest": {
        "n_estimators": 300,
        "max_depth": 5,
        "max_features": "sqrt",
        "max_samples": 0.7,
    },
    "ExtraTrees": {
        "n_estimators": 300,
        "max_depth": 5,
        "max_features": "sqrt",
    },
    "XGBoost": {
        "n_estimators": 300,
        "max_depth": 5,
        "learning_rate": 0.1,
        "subsample": 0.7,
        "colsample_bytree": 0.7,
        "reg_alpha": 0.01,
        "reg_lambda": 1.0,
    },
    "LightGBM": {
        "n_estimators": 300,
        "max_depth": 5,
        "learning_rate": 0.1,
        "num_leaves": 31,
        "subsample": 0.7,
        "colsample_bytree": 0.7,
        "reg_alpha": 0.01,
        "reg_lambda": 1.0,
    },
}

total_exp = len(MODEL_CONFIGS) * len(SINGLE_COVARIATES) * len(WINDOWS) * len(HORIZONS)
print(f"Models    : {list(MODEL_CONFIGS.keys())}")
print(f"Covariates: {len(SINGLE_COVARIATES)} configs")
print(f"Windows   : {WINDOWS}")
print(f"Horizons  : {HORIZONS}")
print(f"Total experiments: {total_exp}")

Models    : ['RandomForest', 'ExtraTrees', 'XGBoost', 'LightGBM']
Covariates: 16 configs
Windows   : [30, 180]
Horizons  : [1, 30]
Total experiments: 256

## 3. Helper Functions

In [7]:
def to_series(df, target_col, covariates=None):
    """Convert DataFrame to Darts TimeSeries (target + optional covariates)."""
    target = TimeSeries.from_dataframe(
        df, time_col="date", value_cols=target_col,
        fill_missing_dates=True, freq="B",
    )
    target = fill_missing_values(target)
    cov = None
    if covariates:
        cov = TimeSeries.from_dataframe(
            df, time_col="date", value_cols=covariates,
            fill_missing_dates=True, freq="B",
        )
        cov = fill_missing_values(cov)
    return target, cov


def build_model(model_name, window, horizon, has_covariates):
    """Factory: build a Darts model dengan window dan horizon yang ditentukan."""
    params = MODEL_CONFIGS[model_name]
    common = {
        "lags": window,
        "lags_past_covariates": window if has_covariates else None,
        "output_chunk_length": horizon,
    }
    if model_name == "RandomForest":
        return RandomForestModel(**common, random_state=42, n_jobs=-1, **params)
    elif model_name == "ExtraTrees":
        return SKLearnModel(
            **common,
            model=ExtraTreesRegressor(random_state=42, n_jobs=-1, **params),
        )
    elif model_name == "XGBoost":
        return XGBModel(**common, random_state=42, n_jobs=-1, **params)
    elif model_name == "LightGBM":
        return LightGBMModel(**common, random_state=42, n_jobs=-1, verbose=-1, **params)
    else:
        raise ValueError(f"Unknown model: {model_name}")


print("Helpers defined")

Helpers defined

## 4. Evaluate Function (5-fold Expanding CV, MAPE on Level)

Pipeline per fold:
1. Split expanding: train[:train_end], test[train_end:test_end]
2. Transform target: `log -> Diff(1) -> Scaler` (fit on train)
3. Transform covariates: `log -> Diff(1)` untuk LEVEL_VARS, `Diff(1)` untuk RATE_VARS, lalu `Scaler`
4. Fit model on train, historical forecast on test window
5. Inverse: scaler -> log-diff -> cumsum dari anchor -> exp -> harga level
6. Compute metrics: MAPE, MAE, RMSE, R2, DA

In [8]:
def train_and_evaluate(model_name, target_ts, cov_ts, window, horizon, n_folds=N_FOLDS):
    """5-fold expanding CV. Returns dict of per-fold metrics."""
    n = len(target_ts)
    test_size = int(n * 0.15)
    min_train = int(n * 0.4)
    available = n - min_train - test_size
    step = max(1, available // max(1, n_folds - 1))

    fold_metrics = {"mape": [], "mae": [], "rmse": [], "r2": [], "da": []}

    for fold in range(n_folds):
        train_end = min_train + fold * step
        test_end = min(train_end + test_size, n)
        if test_end > n or train_end >= test_end:
            break

        train_ts = target_ts[:train_end]
        test_ts  = target_ts[train_end:test_end]
        fold_ts  = target_ts[:test_end]

        # Target transform: log -> diff -> scale (fit on train)
        train_log = train_ts.map(np.log)
        fold_log  = fold_ts.map(np.log)
        differencer = Diff(lags=1)
        train_log_diff = differencer.fit_transform(train_log)
        fold_log_diff  = differencer.transform(fold_log)
        scaler = Scaler()
        train_scaled = scaler.fit_transform(train_log_diff)
        fold_scaled  = scaler.transform(fold_log_diff)

        # Covariate transform
        cov_transformed = None
        if cov_ts is not None:
            cov_fold  = cov_ts[:test_end]
            cov_train = cov_ts[:train_end]
            cov_cols   = cov_ts.components.tolist()
            level_cols = [c for c in cov_cols if c in LEVEL_VARS]
            rate_cols  = [c for c in cov_cols if c in RATE_VARS]

            parts_train, parts_fold = [], []
            if level_cols:
                d1 = Diff(lags=1)
                parts_train.append(d1.fit_transform(cov_train[level_cols].map(np.log)))
                parts_fold.append(d1.transform(cov_fold[level_cols].map(np.log)))
            if rate_cols:
                d2 = Diff(lags=1)
                parts_train.append(d2.fit_transform(cov_train[rate_cols]))
                parts_fold.append(d2.transform(cov_fold[rate_cols]))

            ct = parts_train[0]
            cf = parts_fold[0]
            for pt, pf in zip(parts_train[1:], parts_fold[1:]):
                ct = ct.stack(pt)
                cf = cf.stack(pf)

            cov_scaler = Scaler()
            cov_scaler.fit(ct)
            cov_transformed = cov_scaler.transform(cf)

        # Fit model (sekarang terima horizon)
        model = build_model(model_name, window, horizon, has_covariates=(cov_ts is not None))
        model.fit(train_scaled, past_covariates=cov_transformed)

        # Historical forecast — stride = horizon agar non-overlapping
        forecast_list = model.historical_forecasts(
            series=fold_scaled,
            past_covariates=cov_transformed,
            start=test_ts.start_time(),
            forecast_horizon=horizon,
            stride=horizon,
            retrain=False,
            last_points_only=False,
            verbose=False,
        )
        if isinstance(forecast_list, TimeSeries):
            forecast_list = [forecast_list]

        # Inverse transform ke level harga IHSG
        all_dates, all_prices = [], []
        fold_log_full = fold_ts.map(np.log)
        for chunk_scaled in forecast_list:
            chunk_diff = scaler.inverse_transform(chunk_scaled)
            dates = chunk_diff.time_index
            vals  = chunk_diff.values().flatten()
            idx   = fold_ts.get_index_at_point(dates[0])
            if idx == 0:
                continue
            anchor     = fold_log_full[idx - 1].values()[0][0]
            log_prices = anchor + np.cumsum(vals)
            all_dates.extend(dates)
            all_prices.extend(np.exp(log_prices))

        # Metrics
        pred_df   = pd.DataFrame({"date": pd.to_datetime(all_dates), "predicted": all_prices})
        actual_df = fold_ts.to_dataframe().reset_index()
        actual_df.columns = ["date", "actual"]
        eval_df = pd.merge(actual_df, pred_df, on="date", how="inner")
        y_true  = eval_df["actual"].values
        y_pred  = eval_df["predicted"].values

        mape   = np.mean(np.abs((y_true - y_pred) / y_true)) * 100
        mae    = np.mean(np.abs(y_true - y_pred))
        rmse   = np.sqrt(np.mean((y_true - y_pred) ** 2))
        ss_res = np.sum((y_true - y_pred) ** 2)
        ss_tot = np.sum((y_true - y_true.mean()) ** 2)
        r2     = 1 - (ss_res / ss_tot) if ss_tot > 0 else np.nan
        actual_dir = np.diff(y_true)
        pred_dir   = y_pred[1:] - y_true[:-1]
        da = np.mean((actual_dir > 0) == (pred_dir > 0)) * 100 if len(actual_dir) > 0 else np.nan

        fold_metrics["mape"].append(mape)
        fold_metrics["mae"].append(mae)
        fold_metrics["rmse"].append(rmse)
        fold_metrics["r2"].append(r2)
        fold_metrics["da"].append(da)

        del model
        gc.collect()

    return fold_metrics


print("Evaluation function defined")

Evaluation function defined

## 5. Run Experiment Loop (128 experiments)

In [9]:
results = []
start_time = datetime.now()
exp_num = 0
print(f"Phase 1 Screening started: {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
print(f"Total experiments: {total_exp}")
print("=" * 75)

for model_name in MODEL_CONFIGS.keys():
    for cov_name, cov_vars in SINGLE_COVARIATES.items():
        for window in WINDOWS:
            for horizon in HORIZONS:
                exp_num += 1
                tag = f"[{exp_num}/{total_exp}] {model_name:13s} | {cov_name:16s} | W{window}_H{horizon}"
                try:
                    target_ts, cov_ts = to_series(
                        df_merged, "IHSG", cov_vars if cov_vars else None
                    )
                    fm = train_and_evaluate(model_name, target_ts, cov_ts, window, horizon)

                    row = {
                        "Model":     model_name,
                        "Covariates": cov_name,
                        "Window":    window,
                        "Horizon":   horizon,
                        "MAPE_mean": round(np.mean(fm["mape"]), 4),
                        "MAPE_std":  round(np.std(fm["mape"]), 4),
                        "MAE_mean":  round(np.mean(fm["mae"]), 4),
                        "RMSE_mean": round(np.mean(fm["rmse"]), 4),
                        "RMSE_std":  round(np.std(fm["rmse"]), 4),
                        "R2_mean":   round(np.mean(fm["r2"]), 4),
                        "DA_mean":   round(np.mean(fm["da"]), 2),
                        "DA_std":    round(np.std(fm["da"]), 2),
                    }
                    results.append(row)
                    print(f"{tag} -> MAPE={row['MAPE_mean']:.4f}+-{row['MAPE_std']:.4f}% | DA={row['DA_mean']:.1f}%")
                except Exception as e:
                    print(f"{tag} -> ERROR: {e}")
                    traceback.print_exc()
                    results.append({
                        "Model": model_name, "Covariates": cov_name,
                        "Window": window, "Horizon": horizon, "Error": str(e),
                    })

elapsed = datetime.now() - start_time
print("=" * 75)
print(f"Done in {elapsed}")

df_results = pd.DataFrame(results)
df_results.to_csv("phase1_screening_results.csv", index=False)
print(f"Saved: phase1_screening_results.csv ({len(df_results)} rows)")
display(df_results.sort_values("MAPE_mean").head(20))

Phase 1 Screening started: 2026-05-04 12:45:12
Total experiments: 256
===========================================================================
[1/256] RandomForest  | None             | W30_H1 -> MAPE=0.6666+-0.1721% | DA=50.7%
[2/256] RandomForest  | None             | W30_H30 -> MAPE=2.6953+-0.9643% | DA=49.6%
[3/256] RandomForest  | None             | W120_H1 -> MAPE=0.6626+-0.1674% | DA=52.3%
[4/256] RandomForest  | None             | W120_H30 -> MAPE=2.7055+-0.9644% | DA=50.0%
[5/256] RandomForest  | BI_Rate          | W30_H1 -> MAPE=0.6645+-0.1696% | DA=51.4%
[6/256] RandomForest  | BI_Rate          | W30_H30 -> MAPE=2.6875+-0.9543% | DA=49.7%
[7/256] RandomForest  | BI_Rate          | W120_H1 -> MAPE=0.6629+-0.1684% | DA=50.2%
[8/256] RandomForest  | BI_Rate          | W120_H30 -> MAPE=2.7040+-0.9645% | DA=49.9%
[9/256] RandomForest  | CPI              | W30_H1 -> MAPE=0.6636+-0.1691% | DA=52.3%
[10/256] RandomForest  | CPI              | W30_H30 -> MAPE=2.6900+-0.9548% | DA=49.7%
[11/256] RandomForest  | CPI              | W120_H1 -> MAPE=0.6615+-0.1657% | DA=52.0%
[12/256] RandomForest  | CPI              | W120_H30 -> MAPE=2.6928+-0.9483% | DA=49.8%
[13/256] RandomForest  | M2               | W30_H1 -> MAPE=0.6634+-0.1687% | DA=52.3%
[14/256] RandomForest  | M2               | W30_H30 -> MAPE=2.6890+-0.9550% | DA=49.7%
[15/256] RandomForest  | M2               | W120_H1 -> MAPE=0.6612+-0.1658% | DA=51.9%
[16/256] RandomForest  | M2               | W120_H30 -> MAPE=2.7041+-0.9665% | DA=49.8%
[17/256] RandomForest  | NPL_Ratio        | W30_H1 -> MAPE=0.6638+-0.1698% | DA=52.1%
[18/256] RandomForest  | NPL_Ratio        | W30_H30 -> MAPE=2.6934+-0.9632% | DA=49.5%
[19/256] RandomForest  | NPL_Ratio        | W120_H1 -> MAPE=0.6612+-0.1658% | DA=52.3%
[20/256] RandomForest  | NPL_Ratio        | W120_H30 -> MAPE=2.6937+-0.9606% | DA=49.9%
[21/256] RandomForest  | USDIDR           | W30_H1 -> MAPE=0.6630+-0.1682% | DA=51.3%
[22/256] RandomForest  | USDIDR           | W30_H30 -> MAPE=2.6851+-0.9486% | DA=49.4%
[23/256] RandomForest  | USDIDR           | W120_H1 -> MAPE=0.6626+-0.1679% | DA=51.1%
[24/256] RandomForest  | USDIDR           | W120_H30 -> MAPE=2.7057+-0.9622% | DA=50.1%
[25/256] RandomForest  | GDP              | W30_H1 -> MAPE=0.6641+-0.1696% | DA=52.0%
[26/256] RandomForest  | GDP              | W30_H30 -> MAPE=2.6938+-0.9657% | DA=49.4%
[27/256] RandomForest  | GDP              | W120_H1 -> MAPE=0.6619+-0.1673% | DA=51.6%
[28/256] RandomForest  | GDP              | W120_H30 -> MAPE=2.7095+-0.9682% | DA=49.9%
[29/256] RandomForest  | US_Treasury_10Y  | W30_H1 -> MAPE=0.6658+-0.1646% | DA=49.7%
[30/256] RandomForest  | US_Treasury_10Y  | W30_H30 -> MAPE=2.6853+-0.9085% | DA=49.4%
[31/256] RandomForest  | US_Treasury_10Y  | W120_H1 -> MAPE=0.6618+-0.1624% | DA=50.5%
[32/256] RandomForest  | US_Treasury_10Y  | W120_H30 -> MAPE=2.6793+-0.9503% | DA=49.2%
[33/256] RandomForest  | Coal             | W30_H1 -> MAPE=0.6656+-0.1695% | DA=51.0%
[34/256] RandomForest  | Coal             | W30_H30 -> MAPE=2.6906+-0.9535% | DA=49.4%
[35/256] RandomForest  | Coal             | W120_H1 -> MAPE=0.6634+-0.1657% | DA=50.2%
[36/256] RandomForest  | Coal             | W120_H30 -> MAPE=2.7159+-0.9521% | DA=49.9%
[37/256] RandomForest  | Copper           | W30_H1 -> MAPE=0.6645+-0.1694% | DA=50.7%
[38/256] RandomForest  | Copper           | W30_H30 -> MAPE=2.7033+-0.9347% | DA=49.0%
[39/256] RandomForest  | Copper           | W120_H1 -> MAPE=0.6626+-0.1669% | DA=50.9%
[40/256] RandomForest  | Copper           | W120_H30 -> MAPE=2.7013+-0.9418% | DA=49.9%
[41/256] RandomForest  | Nickel           | W30_H1 -> MAPE=0.6639+-0.1680% | DA=50.6%
[42/256] RandomForest  | Nickel           | W30_H30 -> MAPE=2.6958+-0.9517% | DA=49.7%
[43/256] RandomForest  | Nickel           | W120_H1 -> MAPE=0.6639+-0.1660% | DA=49.2%
[44/256] RandomForest  | Nickel           | W120_H30 -> MAPE=2.7203+-0.9373% | DA=50.4%
[45/256] RandomForest  | Silver           | W30_H1 -> MAPE=0.6628+-0.1687% | DA=53.1%
[46/256] RandomForest  | Silver           | W30_H30 -> MAPE=2.6905+-0.9608% | DA=49.7%
[47/256] RandomForest  | Silver           | W120_H1 -> MAPE=0.6623+-0.1686% | DA=51.6%
[48/256] RandomForest  | Silver           | W120_H30 -> MAPE=2.6896+-0.9623% | DA=50.0%
[49/256] RandomForest  | Tin              | W30_H1 -> MAPE=0.6633+-0.1651% | DA=51.8%
[50/256] RandomForest  | Tin              | W30_H30 -> MAPE=2.7048+-0.9315% | DA=49.3%
[51/256] RandomForest  | Tin              | W120_H1 -> MAPE=0.6623+-0.1654% | DA=50.5%
[52/256] RandomForest  | Tin              | W120_H30 -> MAPE=2.6955+-0.9313% | DA=49.2%
[53/256] RandomForest  | Gold             | W30_H1 -> MAPE=0.6599+-0.1654% | DA=53.4%
[54/256] RandomForest  | Gold             | W30_H30 -> MAPE=2.6880+-0.9556% | DA=49.6%
[55/256] RandomForest  | Gold             | W120_H1 -> MAPE=0.6617+-0.1673% | DA=51.1%
[56/256] RandomForest  | Gold             | W120_H30 -> MAPE=2.6931+-0.9544% | DA=50.2%
[57/256] RandomForest  | WTI              | W30_H1 -> MAPE=0.6636+-0.1698% | DA=51.5%
[58/256] RandomForest  | WTI              | W30_H30 -> MAPE=2.6844+-0.9587% | DA=49.3%
[59/256] RandomForest  | WTI              | W120_H1 -> MAPE=0.6619+-0.1680% | DA=51.0%
[60/256] RandomForest  | WTI              | W120_H30 -> MAPE=2.6913+-0.9558% | DA=50.1%
[61/256] RandomForest  | STI              | W30_H1 -> MAPE=0.6633+-0.1673% | DA=52.9%
[62/256] RandomForest  | STI              | W30_H30 -> MAPE=2.6957+-0.9540% | DA=49.5%
[63/256] RandomForest  | STI              | W120_H1 -> MAPE=0.6627+-0.1673% | DA=52.3%
[64/256] RandomForest  | STI              | W120_H30 -> MAPE=2.7084+-0.9657% | DA=50.1%
[65/256] ExtraTrees    | None             | W30_H1 -> MAPE=0.6609+-0.1655% | DA=51.8%
[66/256] ExtraTrees    | None             | W30_H30 -> MAPE=2.6957+-0.9614% | DA=49.3%
[67/256] ExtraTrees    | None             | W120_H1 -> MAPE=0.6599+-0.1645% | DA=52.6%
[68/256] ExtraTrees    | None             | W120_H30 -> MAPE=2.7036+-0.9669% | DA=49.6%
[69/256] ExtraTrees    | BI_Rate          | W30_H1 -> MAPE=0.6601+-0.1637% | DA=52.4%
[70/256] ExtraTrees    | BI_Rate          | W30_H30 -> MAPE=2.6965+-0.9652% | DA=49.2%
[71/256] ExtraTrees    | BI_Rate          | W120_H1 -> MAPE=0.6593+-0.1636% | DA=51.1%
[72/256] ExtraTrees    | BI_Rate          | W120_H30 -> MAPE=2.6929+-0.9537% | DA=49.9%
[73/256] ExtraTrees    | CPI              | W30_H1 -> MAPE=0.6593+-0.1636% | DA=51.9%
[74/256] ExtraTrees    | CPI              | W30_H30 -> MAPE=2.6961+-0.9606% | DA=49.2%
[75/256] ExtraTrees    | CPI              | W120_H1 -> MAPE=0.6590+-0.1629% | DA=51.8%
[76/256] ExtraTrees    | CPI              | W120_H30 -> MAPE=2.6819+-0.9443% | DA=49.8%
[77/256] ExtraTrees    | M2               | W30_H1 -> MAPE=0.6597+-0.1625% | DA=52.2%
[78/256] ExtraTrees    | M2               | W30_H30 -> MAPE=2.6955+-0.9584% | DA=49.1%
[79/256] ExtraTrees    | M2               | W120_H1 -> MAPE=0.6597+-0.1627% | DA=51.9%
[80/256] ExtraTrees    | M2               | W120_H30 -> MAPE=2.6997+-0.9541% | DA=49.7%
[81/256] ExtraTrees    | NPL_Ratio        | W30_H1 -> MAPE=0.6599+-0.1639% | DA=51.5%
[82/256] ExtraTrees    | NPL_Ratio        | W30_H30 -> MAPE=2.6952+-0.9628% | DA=49.1%
[83/256] ExtraTrees    | NPL_Ratio        | W120_H1 -> MAPE=0.6593+-0.1637% | DA=52.2%
[84/256] ExtraTrees    | NPL_Ratio        | W120_H30 -> MAPE=2.6923+-0.9555% | DA=49.9%
[85/256] ExtraTrees    | USDIDR           | W30_H1 -> MAPE=0.6594+-0.1637% | DA=52.2%
[86/256] ExtraTrees    | USDIDR           | W30_H30 -> MAPE=2.6947+-0.9606% | DA=49.3%
[87/256] ExtraTrees    | USDIDR           | W120_H1 -> MAPE=0.6601+-0.1645% | DA=51.5%
[88/256] ExtraTrees    | USDIDR           | W120_H30 -> MAPE=2.7041+-0.9700% | DA=49.8%
[89/256] ExtraTrees    | GDP              | W30_H1 -> MAPE=0.6601+-0.1646% | DA=52.5%
[90/256] ExtraTrees    | GDP              | W30_H30 -> MAPE=2.6932+-0.9603% | DA=49.3%
[91/256] ExtraTrees    | GDP              | W120_H1 -> MAPE=0.6587+-0.1633% | DA=52.5%
[92/256] ExtraTrees    | GDP              | W120_H30 -> MAPE=2.6947+-0.9560% | DA=49.7%
[93/256] ExtraTrees    | US_Treasury_10Y  | W30_H1 -> MAPE=0.6590+-0.1632% | DA=52.3%
[94/256] ExtraTrees    | US_Treasury_10Y  | W30_H30 -> MAPE=2.6922+-0.9499% | DA=49.2%
[95/256] ExtraTrees    | US_Treasury_10Y  | W120_H1 -> MAPE=0.6597+-0.1635% | DA=51.6%
[96/256] ExtraTrees    | US_Treasury_10Y  | W120_H30 -> MAPE=2.6888+-0.9490% | DA=49.7%
[97/256] ExtraTrees    | Coal             | W30_H1 -> MAPE=0.6596+-0.1637% | DA=53.3%
[98/256] ExtraTrees    | Coal             | W30_H30 -> MAPE=2.6989+-0.9608% | DA=49.3%
[99/256] ExtraTrees    | Coal             | W120_H1 -> MAPE=0.6603+-0.1640% | DA=50.4%
[100/256] ExtraTrees    | Coal             | W120_H30 -> MAPE=2.7007+-0.9586% | DA=49.9%
[101/256] ExtraTrees    | Copper           | W30_H1 -> MAPE=0.6586+-0.1628% | DA=51.7%
[102/256] ExtraTrees    | Copper           | W30_H30 -> MAPE=2.6869+-0.9484% | DA=49.2%
[103/256] ExtraTrees    | Copper           | W120_H1 -> MAPE=0.6590+-0.1633% | DA=52.6%
[104/256] ExtraTrees    | Copper           | W120_H30 -> MAPE=2.6967+-0.9554% | DA=49.9%
[105/256] ExtraTrees    | Nickel           | W30_H1 -> MAPE=0.6599+-0.1633% | DA=51.5%
[106/256] ExtraTrees    | Nickel           | W30_H30 -> MAPE=2.6946+-0.9546% | DA=49.5%
[107/256] ExtraTrees    | Nickel           | W120_H1 -> MAPE=0.6599+-0.1644% | DA=51.3%
[108/256] ExtraTrees    | Nickel           | W120_H30 -> MAPE=2.6873+-0.9548% | DA=49.5%
[109/256] ExtraTrees    | Silver           | W30_H1 -> MAPE=0.6581+-0.1624% | DA=54.1%
[110/256] ExtraTrees    | Silver           | W30_H30 -> MAPE=2.6924+-0.9612% | DA=49.5%
[111/256] ExtraTrees    | Silver           | W120_H1 -> MAPE=0.6586+-0.1634% | DA=53.2%
[112/256] ExtraTrees    | Silver           | W120_H30 -> MAPE=2.6971+-0.9638% | DA=49.9%
[113/256] ExtraTrees    | Tin              | W30_H1 -> MAPE=0.6590+-0.1628% | DA=51.7%
[114/256] ExtraTrees    | Tin              | W30_H30 -> MAPE=2.6972+-0.9498% | DA=49.2%
[115/256] ExtraTrees    | Tin              | W120_H1 -> MAPE=0.6592+-0.1623% | DA=50.9%
[116/256] ExtraTrees    | Tin              | W120_H30 -> MAPE=2.6969+-0.9520% | DA=49.2%
[117/256] ExtraTrees    | Gold             | W30_H1 -> MAPE=0.6583+-0.1622% | DA=52.9%
[118/256] ExtraTrees    | Gold             | W30_H30 -> MAPE=2.6962+-0.9599% | DA=49.5%
[119/256] ExtraTrees    | Gold             | W120_H1 -> MAPE=0.6590+-0.1637% | DA=52.6%
[120/256] ExtraTrees    | Gold             | W120_H30 -> MAPE=2.6950+-0.9612% | DA=50.0%
[121/256] ExtraTrees    | WTI              | W30_H1 -> MAPE=0.6583+-0.1623% | DA=51.6%
[122/256] ExtraTrees    | WTI              | W30_H30 -> MAPE=2.6922+-0.9613% | DA=49.5%
[123/256] ExtraTrees    | WTI              | W120_H1 -> MAPE=0.6586+-0.1629% | DA=52.2%
[124/256] ExtraTrees    | WTI              | W120_H30 -> MAPE=2.6953+-0.9606% | DA=49.8%
[125/256] ExtraTrees    | STI              | W30_H1 -> MAPE=0.6603+-0.1640% | DA=52.8%
[126/256] ExtraTrees    | STI              | W30_H30 -> MAPE=2.7223+-0.9935% | DA=49.1%
[127/256] ExtraTrees    | STI              | W120_H1 -> MAPE=0.6594+-0.1643% | DA=53.9%
[128/256] ExtraTrees    | STI              | W120_H30 -> MAPE=2.7180+-0.9792% | DA=49.8%
[129/256] XGBoost       | None             | W30_H1 -> MAPE=0.6978+-0.1766% | DA=51.8%
[130/256] XGBoost       | None             | W30_H30 -> MAPE=3.0103+-1.0734% | DA=48.7%
[131/256] XGBoost       | None             | W120_H1 -> MAPE=0.6999+-0.1649% | DA=50.2%
[132/256] XGBoost       | None             | W120_H30 -> MAPE=3.0353+-0.9354% | DA=49.1%
[133/256] XGBoost       | BI_Rate          | W30_H1 -> MAPE=0.7158+-0.1729% | DA=49.1%
[134/256] XGBoost       | BI_Rate          | W30_H30 -> MAPE=2.9404+-1.0063% | DA=49.0%
[135/256] XGBoost       | BI_Rate          | W120_H1 -> MAPE=0.6995+-0.1703% | DA=51.4%
[136/256] XGBoost       | BI_Rate          | W120_H30 -> MAPE=3.1236+-1.0437% | DA=47.9%
[137/256] XGBoost       | CPI              | W30_H1 -> MAPE=0.7114+-0.1731% | DA=51.4%
[138/256] XGBoost       | CPI              | W30_H30 -> MAPE=2.8784+-0.9492% | DA=49.4%
[139/256] XGBoost       | CPI              | W120_H1 -> MAPE=0.6995+-0.1672% | DA=50.5%
[140/256] XGBoost       | CPI              | W120_H30 -> MAPE=2.8867+-0.9394% | DA=49.1%
[141/256] XGBoost       | M2               | W30_H1 -> MAPE=0.7125+-0.1802% | DA=51.0%
[142/256] XGBoost       | M2               | W30_H30 -> MAPE=3.0844+-1.0428% | DA=49.0%
[143/256] XGBoost       | M2               | W120_H1 -> MAPE=0.7031+-0.1655% | DA=50.9%
[144/256] XGBoost       | M2               | W120_H30 -> MAPE=2.9722+-0.9613% | DA=49.6%
[145/256] XGBoost       | NPL_Ratio        | W30_H1 -> MAPE=0.7109+-0.1710% | DA=50.3%
[146/256] XGBoost       | NPL_Ratio        | W30_H30 -> MAPE=3.0443+-1.1175% | DA=49.2%
[147/256] XGBoost       | NPL_Ratio        | W120_H1 -> MAPE=0.7053+-0.1684% | DA=51.1%
[148/256] XGBoost       | NPL_Ratio        | W120_H30 -> MAPE=3.0511+-0.9097% | DA=49.7%
[149/256] XGBoost       | USDIDR           | W30_H1 -> MAPE=0.7031+-0.1671% | DA=51.1%
[150/256] XGBoost       | USDIDR           | W30_H30 -> MAPE=2.8142+-0.9536% | DA=48.7%
[151/256] XGBoost       | USDIDR           | W120_H1 -> MAPE=0.6954+-0.1570% | DA=52.9%
[152/256] XGBoost       | USDIDR           | W120_H30 -> MAPE=3.0645+-1.1144% | DA=49.3%
[153/256] XGBoost       | GDP              | W30_H1 -> MAPE=0.7109+-0.1807% | DA=50.6%
[154/256] XGBoost       | GDP              | W30_H30 -> MAPE=3.0322+-0.9235% | DA=49.7%
[155/256] XGBoost       | GDP              | W120_H1 -> MAPE=0.6977+-0.1605% | DA=51.1%
[156/256] XGBoost       | GDP              | W120_H30 -> MAPE=3.0155+-0.9232% | DA=49.1%
[157/256] XGBoost       | US_Treasury_10Y  | W30_H1 -> MAPE=0.7193+-0.1518% | DA=51.7%
[158/256] XGBoost       | US_Treasury_10Y  | W30_H30 -> MAPE=3.3510+-0.9925% | DA=49.5%
[159/256] XGBoost       | US_Treasury_10Y  | W120_H1 -> MAPE=0.7361+-0.1418% | DA=48.5%
[160/256] XGBoost       | US_Treasury_10Y  | W120_H30 -> MAPE=3.3723+-0.7247% | DA=49.1%
[161/256] XGBoost       | Coal             | W30_H1 -> MAPE=0.7251+-0.1703% | DA=50.1%
[162/256] XGBoost       | Coal             | W30_H30 -> MAPE=3.0757+-0.9875% | DA=48.0%
[163/256] XGBoost       | Coal             | W120_H1 -> MAPE=0.7200+-0.1664% | DA=48.1%
[164/256] XGBoost       | Coal             | W120_H30 -> MAPE=3.3127+-0.8774% | DA=48.0%
[165/256] XGBoost       | Copper           | W30_H1 -> MAPE=0.7098+-0.1801% | DA=52.1%
[166/256] XGBoost       | Copper           | W30_H30 -> MAPE=3.0123+-0.9939% | DA=50.1%
[167/256] XGBoost       | Copper           | W120_H1 -> MAPE=0.7108+-0.1775% | DA=49.1%
[168/256] XGBoost       | Copper           | W120_H30 -> MAPE=3.0313+-1.0508% | DA=49.0%
[169/256] XGBoost       | Nickel           | W30_H1 -> MAPE=0.7125+-0.1693% | DA=50.5%
[170/256] XGBoost       | Nickel           | W30_H30 -> MAPE=3.0204+-0.8255% | DA=50.2%
[171/256] XGBoost       | Nickel           | W120_H1 -> MAPE=0.7039+-0.1627% | DA=49.6%
[172/256] XGBoost       | Nickel           | W120_H30 -> MAPE=3.2723+-0.7754% | DA=49.3%
[173/256] XGBoost       | Silver           | W30_H1 -> MAPE=0.7102+-0.1651% | DA=50.8%
[174/256] XGBoost       | Silver           | W30_H30 -> MAPE=3.0939+-1.1520% | DA=49.1%
[175/256] XGBoost       | Silver           | W120_H1 -> MAPE=0.7071+-0.1629% | DA=49.8%
[176/256] XGBoost       | Silver           | W120_H30 -> MAPE=2.9648+-0.9042% | DA=49.5%
[177/256] XGBoost       | Tin              | W30_H1 -> MAPE=0.7144+-0.1648% | DA=50.5%
[178/256] XGBoost       | Tin              | W30_H30 -> MAPE=3.1803+-0.7368% | DA=48.7%
[179/256] XGBoost       | Tin              | W120_H1 -> MAPE=0.7153+-0.1540% | DA=50.6%
[180/256] XGBoost       | Tin              | W120_H30 -> MAPE=3.1013+-0.8635% | DA=48.1%
[181/256] XGBoost       | Gold             | W30_H1 -> MAPE=0.7043+-0.1697% | DA=50.7%
[182/256] XGBoost       | Gold             | W30_H30 -> MAPE=3.1624+-1.1120% | DA=48.3%
[183/256] XGBoost       | Gold             | W120_H1 -> MAPE=0.7036+-0.1631% | DA=51.2%
[184/256] XGBoost       | Gold             | W120_H30 -> MAPE=2.8336+-0.9861% | DA=48.6%
[185/256] XGBoost       | WTI              | W30_H1 -> MAPE=0.7056+-0.1768% | DA=51.4%
[186/256] XGBoost       | WTI              | W30_H30 -> MAPE=2.9842+-0.9953% | DA=48.7%
[187/256] XGBoost       | WTI              | W120_H1 -> MAPE=0.7062+-0.1654% | DA=49.9%
[188/256] XGBoost       | WTI              | W120_H30 -> MAPE=3.0517+-1.1307% | DA=48.9%
[189/256] XGBoost       | STI              | W30_H1 -> MAPE=0.7040+-0.1717% | DA=50.6%
[190/256] XGBoost       | STI              | W30_H30 -> MAPE=3.0986+-1.0915% | DA=49.9%
[191/256] XGBoost       | STI              | W120_H1 -> MAPE=0.7039+-0.1707% | DA=50.5%
[192/256] XGBoost       | STI              | W120_H30 -> MAPE=3.0697+-1.1224% | DA=49.5%
[193/256] LightGBM      | None             | W30_H1 -> MAPE=0.7177+-0.1772% | DA=49.4%
[194/256] LightGBM      | None             | W30_H30 -> MAPE=2.9741+-1.0193% | DA=49.4%
[195/256] LightGBM      | None             | W120_H1 -> MAPE=0.7043+-0.1721% | DA=50.6%
[196/256] LightGBM      | None             | W120_H30 -> MAPE=3.0340+-0.8658% | DA=49.0%
[197/256] LightGBM      | BI_Rate          | W30_H1 -> MAPE=0.7148+-0.1787% | DA=50.6%
[198/256] LightGBM      | BI_Rate          | W30_H30 -> MAPE=2.9930+-1.0026% | DA=49.3%
[199/256] LightGBM      | BI_Rate          | W120_H1 -> MAPE=0.7066+-0.1700% | DA=50.9%
[200/256] LightGBM      | BI_Rate          | W120_H30 -> MAPE=2.9720+-0.9114% | DA=49.3%
[201/256] LightGBM      | CPI              | W30_H1 -> MAPE=0.7261+-0.1735% | DA=48.8%
[202/256] LightGBM      | CPI              | W30_H30 -> MAPE=2.9779+-0.9756% | DA=49.8%
[203/256] LightGBM      | CPI              | W120_H1 -> MAPE=0.7074+-0.1751% | DA=51.5%
[204/256] LightGBM      | CPI              | W120_H30 -> MAPE=3.0255+-0.7908% | DA=48.2%
[205/256] LightGBM      | M2               | W30_H1 -> MAPE=0.7171+-0.1769% | DA=51.0%
[206/256] LightGBM      | M2               | W30_H30 -> MAPE=2.9368+-1.0282% | DA=49.8%
[207/256] LightGBM      | M2               | W120_H1 -> MAPE=0.7011+-0.1685% | DA=51.9%
[208/256] LightGBM      | M2               | W120_H30 -> MAPE=3.0337+-0.8836% | DA=48.5%
[209/256] LightGBM      | NPL_Ratio        | W30_H1 -> MAPE=0.7155+-0.1725% | DA=50.0%
[210/256] LightGBM      | NPL_Ratio        | W30_H30 -> MAPE=3.0665+-0.9805% | DA=49.3%
[211/256] LightGBM      | NPL_Ratio        | W120_H1 -> MAPE=0.7084+-0.1658% | DA=49.9%
[212/256] LightGBM      | NPL_Ratio        | W120_H30 -> MAPE=3.0483+-0.8479% | DA=48.1%
[213/256] LightGBM      | USDIDR           | W30_H1 -> MAPE=0.6987+-0.1662% | DA=53.0%
[214/256] LightGBM      | USDIDR           | W30_H30 -> MAPE=2.9020+-1.0205% | DA=49.0%
[215/256] LightGBM      | USDIDR           | W120_H1 -> MAPE=0.7013+-0.1619% | DA=51.0%
[216/256] LightGBM      | USDIDR           | W120_H30 -> MAPE=3.0200+-0.9615% | DA=48.8%
[217/256] LightGBM      | GDP              | W30_H1 -> MAPE=0.7235+-0.1801% | DA=49.7%
[218/256] LightGBM      | GDP              | W30_H30 -> MAPE=2.9753+-0.8810% | DA=49.4%
[219/256] LightGBM      | GDP              | W120_H1 -> MAPE=0.7061+-0.1738% | DA=50.6%
[220/256] LightGBM      | GDP              | W120_H30 -> MAPE=3.0531+-0.8203% | DA=48.8%
[221/256] LightGBM      | US_Treasury_10Y  | W30_H1 -> MAPE=0.7264+-0.1657% | DA=50.8%
[222/256] LightGBM      | US_Treasury_10Y  | W30_H30 -> MAPE=3.2109+-0.6829% | DA=49.2%
[223/256] LightGBM      | US_Treasury_10Y  | W120_H1 -> MAPE=0.7241+-0.1316% | DA=50.1%
[224/256] LightGBM      | US_Treasury_10Y  | W120_H30 -> MAPE=3.2812+-0.6803% | DA=48.5%
[225/256] LightGBM      | Coal             | W30_H1 -> MAPE=0.7275+-0.1631% | DA=50.3%
[226/256] LightGBM      | Coal             | W30_H30 -> MAPE=3.2854+-0.8742% | DA=47.9%

,Model,Covariates,Window,Horizon,MAPE_mean,MAPE_std,MAE_mean,RMSE_mean,RMSE_std,R2_mean,DA_mean,DA_std
108,ExtraTrees,Silver,30,1,0.6581,0.1624,40.2529,55.0152,9.3042,0.9692,54.10,3.16
120,ExtraTrees,WTI,30,1,0.6583,0.1623,40.2698,55.0262,9.2846,0.9691,51.60,2.05
116,ExtraTrees,Gold,30,1,0.6583,0.1622,40.2697,55.0353,9.3001,0.9691,52.88,2.77
100,ExtraTrees,Copper,30,1,0.6586,0.1628,40.2804,55.0618,9.3728,0.9692,51.70,2.55
110,ExtraTrees,Silver,120,1,0.6586,0.1634,40.2849,55.0116,9.2925,0.9691,53.23,1.90
122,ExtraTrees,WTI,120,1,0.6586,0.1629,40.2885,55.0556,9.2997,0.9691,52.16,2.00
90,ExtraTrees,GDP,120,1,0.6587,0.1633,40.2862,55.0826,9.3521,0.9691,52.52,1.83
102,ExtraTrees,Copper,120,1,0.6590,0.1633,40.3079,55.0752,9.3508,0.9691,52.57,1.60
92,ExtraTrees,US_Treasury_10Y,30,1,0.6590,0.1632,40.3061,55.0489,9.2924,0.9690,52.26,2.36
74,ExtraTrees,CPI,120,1,0.6590,0.1629,40.3148,55.1087,9.3155,0.9690,51.76,2.17
112,ExtraTrees,Tin,30,1,0.6590,0.1628,40.3117,55.1107,9.4218,0.9692,51.70,1.73
118,ExtraTrees,Gold,120,1,0.6590,0.1637,40.3055,55.0800,9.3509,0.9691,52.57,2.44
114,ExtraTrees,Tin,120,1,0.6592,0.1623,40.3260,55.1751,9.2788,0.9689,50.89,0.94
82,ExtraTrees,NPL_Ratio,120,1,0.6593,0.1637,40.3224,55.1315,9.3758,0.9690,52.21,1.01
72,ExtraTrees,CPI,30,1,0.6593,0.1636,40.3191,55.1089,9.3558,0.9691,51.86,0.94
70,ExtraTrees,BI_Rate,120,1,0.6593,0.1636,40.3270,55.1125,9.3967,0.9691,51.15,2.37
126,ExtraTrees,STI,120,1,0.6594,0.1643,40.3260,55.1656,9.4436,0.9691,53.89,1.38
84,ExtraTrees,USDIDR,30,1,0.6594,0.1637,40.3255,55.1301,9.3833,0.9691,52.21,1.24
96,ExtraTrees,Coal,30,1,0.6596,0.1637,40.3400,55.1097,9.3770,0.9691,53.33,1.32
78,ExtraTrees,M2,120,1,0.6597,0.1627,40.3579,55.0991,9.2568,0.9690,51.86,1.70

## 6. Screening Analysis

Covariate dianggap "lolos" kalau improvement MAPE terhadap baseline (`None`) >= threshold. Default threshold = **0.3%** (relative improvement).

In [13]:
def analyze_screening(df, threshold_pct=0.3):
    rows = []
    for model_name in df["Model"].unique():
        for window in df["Window"].unique():
            for horizon in df["Horizon"].unique():
                mask = (
                    (df["Model"]   == model_name) &
                    (df["Window"]  == window) &
                    (df["Horizon"] == horizon)
                )
                subset = df[mask]
                baseline_row = subset[subset["Covariates"] == "None"]
                if baseline_row.empty or "MAPE_mean" not in baseline_row.columns:
                    continue
                baseline_mape = baseline_row["MAPE_mean"].values[0]

                for _, row in subset.iterrows():
                    if row["Covariates"] == "None":
                        continue
                    if pd.isna(row.get("MAPE_mean")):
                        continue
                    impr = (baseline_mape - row["MAPE_mean"]) / baseline_mape * 100
                    rows.append({
                        "Model":          model_name,
                        "Window":         window,
                        "Horizon":        horizon,
                        "Covariate":      row["Covariates"],
                        "MAPE":           row["MAPE_mean"],
                        "Baseline_MAPE":  baseline_mape,
                        "Improvement_pct": round(impr, 3),
                        "Passed":         impr >= threshold_pct,
                    })
    return pd.DataFrame(rows)


df_screening = analyze_screening(df_results, threshold_pct=0.3)
df_screening.to_csv("phase1_screening_analysis.csv", index=False)
print(f"Saved: phase1_screening_analysis.csv ({len(df_screening)} rows)")

# Pass counts (out of 4 models x 2 windows x 2 horizons = 16 combos)
max_combos = df_results["Model"].nunique() * df_results["Window"].nunique() * df_results["Horizon"].nunique()
pass_counts = (
    df_screening[df_screening["Passed"]]
    .groupby("Covariate").size()
    .sort_values(ascending=False)
    .rename("pass_count")
    .to_frame()
)
pass_counts["pass_rate"] = (pass_counts["pass_count"] / max_combos * 100).round(1)
print(f"\nCovariate pass counts (out of {max_combos} model x window x horizon combos):")
display(pass_counts)

# Ringkasan per horizon
print("\nPass counts breakdown per Horizon:")
for h in sorted(df_screening["Horizon"].unique()):
    sub = df_screening[df_screening["Horizon"] == h]
    pc  = sub[sub["Passed"]].groupby("Covariate").size().sort_values(ascending=False)
    max_h = df_results["Model"].nunique() * df_results["Window"].nunique()
    print(f"\n  H{h} (max {max_h} combos):")
    print(f"  {pc.to_dict()}")

Saved: phase1_screening_analysis.csv (240 rows)

Covariate pass counts (out of 16 model x window x horizon combos):

                 pass_count  pass_rate
Covariate
USDIDR                    8       50.0
Gold                      7       43.8
Silver                    7       43.8
WTI                       7       43.8
BI_Rate                   5       31.2
CPI                       5       31.2
Copper                    5       31.2
GDP                       4       25.0
M2                        4       25.0
NPL_Ratio                 4       25.0
Nickel                    4       25.0
STI                       4       25.0
US_Treasury_10Y           3       18.8
Tin                       2       12.5

Pass counts breakdown per Horizon:

  H1 (max 8 combos):
  {'Silver': 4, 'USDIDR': 4, 'Copper': 3, 'Gold': 3, 'Nickel': 3, 'STI': 3, 'BI_Rate': 2, 'GDP': 2, 'M2': 2, 'NPL_Ratio': 2, 'WTI': 2, 'CPI': 1, 'Tin': 1}

  H30 (max 8 combos):
  {'WTI': 5, 'CPI': 4, 'Gold': 4, 'USDIDR': 4, 'BI_Rate': 3, 'Silver': 3, 'US_Treasury_10Y': 3, 'Copper': 2, 'GDP': 2, 'M2': 2, 'NPL_Ratio': 2, 'Nickel': 1, 'STI': 1, 'Tin': 1}